# Generated by Django 4.0.6 on 2022-07-17 13:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200, verbose_name='Endereço')),
                ('phone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('balance', models.FloatField(default=1.0)),
                ('document', models.CharField(choices=[('CPF', 'Pessoa física'), ('CNPJ', 'Pessoa jurídica')], max_length=4, verbose_name='Documento')),
                ('cpf', models.CharField(max_length=11, null=True, verbose_name='CPF')),
                ('cnpj', models.CharField(max_length=14, null=True, verbose_name='CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id_transfer', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(verbose_name='Data')),
                ('value', models.FloatField()),
                ('favored_costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favored', to='digital_bank.costumer', verbose_name='Cliente favorecido')),
                ('requesting_costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesting', to='digital_bank.costumer', verbose_name='Cliente solicitante')),
            ],
        ),
    ]
