# Generated by Django 4.1.1 on 2022-09-06 12:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('address', models.CharField(max_length=200, verbose_name='Endereço')),
                ('phone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('balance', models.FloatField(default=30.0, null=True, verbose_name='Saldo')),
                ('document', models.CharField(choices=[('Physical', 'CPF'), ('Legal', 'CNPJ')], max_length=8, verbose_name='Documento')),
                ('cpf', models.CharField(max_length=11, null=True, verbose_name='CPF')),
                ('cnpj', models.CharField(max_length=14, null=True, verbose_name='CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id_transfer', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 9, 6, 9, 5, 4, 797420), editable=False, verbose_name='Data')),
                ('value', models.FloatField()),
                ('favored_costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favored', to='digital_bank.costumer', verbose_name='Cliente favorecido')),
                ('requesting_costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesting', to='digital_bank.costumer', verbose_name='Cliente solicitante')),
            ],
        ),
    ]
